services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    ports:
      - '3000:3000'
    depends_on:
      - server
    networks:
      - galaxy-net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./server/.env
    networks:
      - galaxy-net

networks:
  galaxy-net:
    driver: bridge
