function insertPRDV2() {
  var doc = DocumentApp.getActiveDocument();
  var tabs = doc.getTabs();
  var secondTab = tabs[1];
  var body = secondTab.asDocumentTab().getBody();
  body.clear();
  function addH1(t){body.appendParagraph(t).setHeading(DocumentApp.ParagraphHeading.HEADING1);}
  function addH2(t){body.appendParagraph(t).setHeading(DocumentApp.ParagraphHeading.HEADING2);}
  function addH3(t){body.appendParagraph(t).setHeading(DocumentApp.ParagraphHeading.HEADING3);}
  function addP(t){body.appendParagraph(t).setHeading(DocumentApp.ParagraphHeading.NORMAL);}
  function addB(t){body.appendListItem(t).setGlyphType(DocumentApp.GlyphType.BULLET);}
  function addBP(b,n){var p=body.appendParagraph('');p.appendText(b).setBold(true);p.appendText(n).setBold(false);}
  body.appendParagraph('Galaxy Notes - Product Requirements Document (PRD) v2').setHeading(DocumentApp.ParagraphHeading.TITLE);
  addBP('Version: ','2.0 (Refined)  |  Date: March 16, 2026  |  Author: Erick Ezrandy  |  Status: Final');
  addBP('Repository: ','github.com/ErickEzrandy274/galaxy-notes');
  addP('');
  addH1('1. Executive Summary');
  addP('Galaxy Notes is a full-stack, production-ready note management platform that enables users to create, organize, share, and collaborate on rich-text notes. Built as a monorepo with a Next.js 16 frontend and NestJS 11 backend, the application provides a modern, responsive experience with real-time notifications, version history tracking, granular sharing permissions, and robust authentication supporting both credential-based and OAuth providers.');
  addP('This document serves as the refined and comprehensive PRD (v2), superseding the initial draft (v1). It reflects the actual implemented architecture, resolves all previously identified edge cases, and defines clear acceptance criteria for every feature module.');
  addH1('2. Problem Statement & Goals');
  addH2('2.1 Problem Statement');
  addP('Individuals and small teams lack a lightweight, self-hostable note-taking application that combines rich-text editing, collaboration features, and granular access control without the complexity and cost of enterprise solutions like Notion or Confluence.');
  addH2('2.2 Product Goals');
  addBP('G1: ','Provide a seamless note creation and editing experience with rich-text support, inline image embedding, PDF attachments, and YouTube video embedding.');
  addBP('G2: ','Enable secure, permission-based note sharing between registered users with READ and WRITE access levels, including email-based invitations for unregistered users.');
  addBP('G3: ','Implement a robust authentication system supporting email/password and OAuth (Google, GitHub, Facebook) with JWT token rotation and stolen token detection.');
  addBP('G4: ','Deliver real-time notifications via Server-Sent Events (SSE) for all collaboration events with intelligent debouncing and rate limiting.');
  addBP('G5: ','Maintain full version history (up to 30 snapshots per note) with diff visualization, allowing users to track changes and restore previous states.');
  addBP('G6: ','Ensure data safety through soft-delete patterns, configurable trash retention, and automated scheduled cleanup via cron jobs.');
  addBP('G7: ','Support containerized deployment via Docker Compose with separate staging and production environments on Vercel (FE), Fly.io (BE), and Supabase (DB).');
  addH2('2.3 Non-Goals (Out of Scope)');
  addBP('NG1: ','Real-time collaborative editing with simultaneous cursors (Google Docs-style). The system uses optimistic locking with conflict detection instead.');
  addBP('NG2: ','Native mobile applications (iOS/Android). The platform is web-only with responsive design.');
  addBP('NG3: ','End-to-end encryption of note content.');
  addBP('NG4: ','Public note publishing, blogging, or SEO features.');
  addBP('NG5: ','Offline-first architecture (limited to localStorage draft recovery).');
  addH1('3. Target Users & Personas');
  addH2('3.1 Primary Persona: Individual Note-Taker');
  addP('A developer, student, or knowledge worker who needs a personal note-taking system with rich-text editing, tagging, and search. They value organization (draft/published/archived states), version history for tracking changes, and the ability to embed media (images, PDFs, YouTube videos) directly within notes.');
  addH2('3.2 Secondary Persona: Small Team Collaborator');
  addP('A team member who needs to share notes with colleagues. They require granular permissions (READ vs WRITE), real-time notifications when shared notes are modified, and the ability to invite external collaborators via email. They expect conflict-free editing with clear version tracking.');
  addH1('4. System Architecture & Tech Stack');
  addH2('4.1 Architecture Overview');
  addP('Galaxy Notes follows a monorepo architecture with three independent workspaces: client (frontend), server (backend), and database (shared Prisma schema). The frontend communicates with the backend via RESTful APIs over HTTPS, with JWT-based authentication. Real-time notifications use Server-Sent Events (SSE) for server-to-client push.');
  addH2('4.2 Frontend (client/)');
  addB('Framework: Next.js 16 with App Router, React 19');
  addB('Authentication: NextAuth v5 (beta) with JWT strategy + OAuth (Google, GitHub, Facebook, Credentials)');
  addB('Styling: Tailwind CSS 4 + Radix UI accessible components');
  addB('State Management: TanStack React Query v5 for server state caching');
  addB('Forms: React Hook Form + Zod validation schemas');
  addB('HTTP Client: Axios with custom JWT interceptor middleware (proactive refresh, reactive retry)');
  addB('Rich Text Editor: react-quill-new with image embedding support');
  addB('File Upload: Supabase Storage via signed URLs (60s TTL)');
  addB('Notifications: react-hot-toast + SSE streaming');
  addB('Icons: Lucide React (20px, consistent stroke-width)');
  addB('Theme: next-themes (dark/light mode, persisted in user preferences)');
  addB('Diff Rendering: diff library for version comparison visualization');
  addH2('4.3 Backend (server/)');
  addB('Framework: NestJS 11 with modular architecture (Controller > Service > DTO pattern)');
  addB('Authentication: Passport.js + JWT strategy with token rotation');
  addB('Password Security: bcrypt with 12 salt rounds');
  addB('Database ORM: Prisma v6 with auto-migrations');
  addB('Email: Nodemailer via Gmail SMTP for password resets and invite emails');
  addB('Scheduled Tasks: @nestjs/schedule for weekly cron cleanup jobs');
  addB('Validation: class-validator + class-transformer for request DTOs');
  addB('File Storage: @supabase/supabase-js for signed URL generation');
  addB('Middleware: RequestIdMiddleware (UUID per request), CsrfMiddleware, LoggingInterceptor');
  addH2('4.4 Database');
  addB('Engine: PostgreSQL hosted on Supabase');
  addB('Connection: PgBouncer pooling (DATABASE_URL) + direct connection for migrations (DIRECT_URL)');
  addB('ORM: Prisma with shared @galaxy-notes/database package');
  addB('File Storage: Supabase Storage with path pattern: {userId}/{noteId}/{timestamp}_{filename}');
  addH2('4.5 Deployment');
  addB('Containerization: Docker Compose with multi-stage builds (deps > builder > runner)');
  addB('Frontend: Vercel (prod: galaxy-notes.vercel.app, staging: dev-galaxy-notes.vercel.app)');
  addB('Backend: Fly.io (prod: galaxy-notes-api.fly.dev, staging: dev-galaxy-notes-api.fly.dev)');
  addB('Database: Supabase PostgreSQL with separate prod and staging instances');
  addB('CI/CD: Merge to staging branch auto-deploys to staging; merge to master auto-deploys to production. Manual production deploy available via GitHub Actions.');
  addH1('5. Data Models');
  addH2('5.1 Core Entities');
  addH3('User');
  addB('id (String, UUID, PK)');
  addB('email (String, unique) - User email address');
  addB('password (String, nullable) - bcrypt hashed; null for OAuth-only users');
  addB('firstName, lastName (String) - Display name');
  addB('bio (String, optional) - Short text description');
  addB('image (String, optional) - Avatar URL from Supabase Storage');
  addB('userType (Enum: general_user | google_user | github_user | facebook_user)');
  addB('createdAt, updatedAt (DateTime)');
  addB('Relations: owns Notes[], receives NoteShares[], has Accounts[], Sessions[], Preferences');
  addH3('Note');
  addB('id (String, UUID, PK)');
  addB('title (String, max 255 characters)');
  addB('content (String, rich-text HTML from Quill editor)');
  addB('status (Enum: draft | published | archived | shared)');
  addB('tags (String[], array for categorization)');
  addB('videoUrl (String, optional) - YouTube embed URL');
  addB('attachmentUrl (String, optional) - PDF attachment URL from Supabase Storage');
  addB('attachmentName, attachmentSize - Original filename and file size in bytes');
  addB('version (Int, default 1) - Optimistic locking counter');
  addB('isDeleted (Boolean, default false), deletedAt (DateTime, optional) - Soft delete fields');
  addB('userId (String, FK to User) - Note owner');
  addB('Relations: NoteVersions[] (max 30), NoteShares[], NoteInvites[], Notifications[]');
  addH3('NoteVersion');
  addB('id (String, UUID, PK), noteId (FK to Note)');
  addB('Snapshot fields: title, content, tags, videoUrl, attachmentUrl, attachmentName, attachmentSize');
  addB('source (Enum: manual_save | autosave)');
  addB('Constraint: Max 30 versions per note; oldest auto-deleted when exceeded');
  addB('Throttle: Autosave versions throttled to 1 per 10 min; manual saves have 30s dedup window');
  addH3('NoteShare');
  addB('id (String, UUID, PK), noteId (FK), userId (FK) - Recipient');
  addB('permission (Enum: READ | WRITE)');
  addB('Unique constraint: (noteId, userId)');
  addH3('NoteInvite');
  addB('id (String, UUID, PK), noteId (FK), email (String)');
  addB('permission (Enum: READ | WRITE), token (unique, 32-byte random)');
  addB('expiresAt (DateTime) - 7-day expiry');
  addH3('Notification');
  addB('id, userId (FK), noteId (optional FK)');
  addB('type (Enum: share | permission_change | leave | revoke | trash | restore | version_cleanup | access_request | access_granted | access_declined_by_owner | etc.)');
  addB('title (String), isRead (Boolean), metadata (JSON, optional)');
  addH3('NotificationMute');
  addB('userId (FK), noteId (FK), expiresAt (optional, null = forever)');
  addB('Options: 1 hour, 1 day, 1 week, forever');
  addH2('5.2 Authentication Entities');
  addH3('RefreshToken');
  addB('token (unique), userId (FK), familyId (String) - Token family for rotation');
  addB('isRevoked (Boolean), expiresAt (24h)');
  addB('Stolen token detection: reused revoked token invalidates entire family');
  addH3('PasswordResetToken');
  addB('token (unique, 32-byte), userId (FK), expiresAt (15 min), isUsed (Boolean)');
  addH3('UserPreference');
  addB('userId (unique FK), trashRetentionDays (default 30)');
  addB('autoDeleteBehavior (Enum: delete_note_and_versions | delete_versions_only)');
  addH1('6. Feature Specifications');
  addH2('6.1 Authentication & User Management');
  addH3('6.1.1 Registration');
  addB('Email/password registration with Zod validation (min 12 chars, uppercase, lowercase, number, special char)');
  addB('Password hashed with bcrypt (12 rounds) before storage');
  addB('JWT access token (1h) + refresh token (24h) issued on registration');
  addB('Refresh token stored as httpOnly secure cookie (path=/api/auth, 24h maxAge)');
  addH3('6.1.2 Login');
  addB('Credential login: Email + password verification via bcrypt.compare()');
  addB('OAuth login: Google, GitHub, Facebook via NextAuth providers');
  addB('OAuth email collision: prompt user to link via password verification before merging');
  addB('Allow dangerous email account linking (multiple OAuth providers per email)');
  addH3('6.1.3 Token Management');
  addB('Access Token: JWT, 1h TTL, stored in NextAuth encrypted cookie + in-memory cache');
  addB('Refresh Token: JWT, 24h TTL, httpOnly cookie + PostgreSQL with familyId');
  addB('Token Rotation: old token revoked, new issued with same familyId');
  addB('Stolen Token Detection: revoked token reuse invalidates entire family');
  addB('Proactive Refresh: Axios interceptor auto-refreshes if token expires in <10 min');
  addB('Periodic Background Refresh: every 5 min + on tab visibility + window focus');
  addB('Reactive Refresh: on 401, attempt refresh + retry; on failure, force logout');
  addH3('6.1.4 Password Reset (Forgot Password)');
  addB('User enters email > 32-byte token generated (15 min expiry) > email sent via Nodemailer/Gmail SMTP');
  addB('Reset link: /reset-password?token=TOKEN');
  addB('Validate token, verify not expired/used, hash new password, mark token used');
  addB('Resend link disabled for 1 min with countdown timer');
  addH3('6.1.5 User Profile Management');
  addB('Editable: firstName, lastName, bio, avatar image');
  addB('Read-only: userType (general/google/github/facebook)');
  addB('Avatar: Supabase Storage signed URL, image/* types');
  addB('Password change: requires current password verification; only for general_user accounts');
  addB('Auto-generate strong password option (min 12, mixed case/number/special)');
  addH2('6.2 Note Management (CRUD)');
  addH3('6.2.1 Create Note');
  addB('Title: max 255 characters (ellipsis in list views)');
  addB('Content: Rich-text via react-quill-new (bold, italic, underline, headers, lists, code blocks, links)');
  addB('Status: draft (default), published, archived, shared');
  addB('Tags: optional array of strings, case-insensitive search');
  addB('Inline Images: max 1MB per image (webp/jpeg/png), via Supabase signed URLs');
  addB('Attachment: single PDF, max 3MB, Supabase Storage');
  addB('YouTube Video: regex-validated URL, rendered in iframe');
  addH3('6.2.2 Read Note');
  addB('Detail view: full rich-text, images, PDF download, YouTube iframe');
  addB('Shared notes: display owner info (name, avatar)');
  addB('Version history: right-side drawer, paginated table, "View Changes" diff in new tab');
  addH3('6.2.3 Update Note');
  addB('Autosave: 2s debounce + localStorage backup every 30s');
  addB('Version snapshots: autosave throttled to 1 per 10 min, manual save 30s dedup');
  addB('Optimistic locking: version number sent with save, 409 Conflict on mismatch');
  addB('Draft notes: no version tracking');
  addB('Orphan cleanup: removed images/attachments auto-deleted from Storage');
  addH3('6.2.4 Note Status Lifecycle');
  addBP('Draft: ','Default state. Cannot be shared or archived. No version tracking.');
  addBP('Published: ','Visible in My Notes. Can be shared, archived, or deleted. Full version tracking.');
  addBP('Shared: ','Has active NoteShare records. Archiving triggers special handling.');
  addBP('Archived: ','Read-only. Hidden from default view. Cannot be deleted directly.');
  addH2('6.3 Rich Text Editor');
  addB('Engine: react-quill-new (lightweight, feature-rich)');
  addB('Toolbar: bold, italic, underline, strikethrough, headers (H1-H3), lists, code blocks, links, image upload, blockquote');
  addB('Image embedding: inline within content, max 1MB, webp/jpeg/png, Supabase signed URLs (60s TTL)');
  addB('YouTube embedding: validated URL in responsive iframe with onError fallback card');
  addB('PDF attachment: single file outside editor, max 3MB, download card with filename and size');
  addB('READ-only mode: editable={false} for READ permission users, edit/save buttons hidden');
  addH2('6.4 Note Sharing & Collaboration');
  addH3('6.4.1 Share Modal UX');
  addB('Email search combobox: type to search registered users (avatar + name + email)');
  addB('Select user to add to pending batch, set permission per user');
  addB('"Invite X user" purple CTA sends all pending invitations');
  addB('Two sections: "Pending invites" (orange) and "Already shared" (purple, editable permission)');
  addB('"No user found" empty state');
  addH3('6.4.2 Sharing Rules');
  addB('Only published or shared notes can be shared (not draft, not archived)');
  addB('Owner can share with READ or WRITE, upgrade/downgrade anytime');
  addB('Shared users can leave voluntarily');
  addB('Shared notes appear on /shared page with filters by permission and owner');
  addH3('6.4.3 Invite Unregistered Users');
  addB('No match: "No account found for [email]" + "Send Invite Email" button');
  addB('Branded email: "You have been invited to view/edit a note by [owner]"');
  addB('Registration link: /register?email=...&invite=TOKEN (email pre-filled, read-only)');
  addB('Token: 32-byte random, 7-day expiry');
  addB('After registration: NoteShare auto-created, user lands on shared note');
  addH3('6.4.4 Sharing Edge Cases');
  addB('Archiving shared note: warning popup > remove all NoteShares > notify users. Previous collaborators can request re-access (1h cooldown).');
  addB('Changing shared to draft: revoke all access, notify: "Your access to [title] revoked by [owner]"');
  addB('Soft-deleting shared note: remove NoteShares, notify: "Note [title] removed by owner"');
  addH2('6.5 Notification System');
  addH3('6.5.1 Delivery');
  addB('Server-Sent Events (SSE): per-user Subject-based stream');
  addB('Client subscribes on login, auto-reconnects');
  addB('Toast popups with type-specific icons and navigation links');
  addH3('6.5.2 Notification Types (15+)');
  addB('share, permission_change, leave, revoke, trash, restore');
  addB('version_cleanup, access_request, access_granted, access_declined_by_owner');
  addB('Each with descriptive title template including note title and actor name');
  addB('Timestamp format: "August 24, 2026 at 10:15 PM"');
  addH3('6.5.3 Rate Limiting & Debouncing');
  addB('Share notifications: 15-min debounce window');
  addB('Edit notifications: max 4/hour per note per collaborator');
  addB('Access requests: 1-hour cooldown per note');
  addH3('6.5.4 Muting');
  addB('Per-note mute: 1 hour, 1 day, 1 week, or forever');
  addB('Expired mutes cleaned by weekly cron');
  addB('Mark all as read functionality');
  addH2('6.6 Version History & Restoration');
  addH3('6.6.1 Version Creation');
  addB('Auto snapshot on every tracked save (manual or autosave)');
  addB('Draft notes excluded from tracking');
  addB('Autosave: max 1 per 10 min; Manual: 30s dedup');
  addB('Snapshot stores: title, content, tags, videoUrl, attachment fields, source');
  addH3('6.6.2 Storage Cap');
  addB('Max 30 versions per note (hard limit)');
  addB('Oldest auto-deleted on new creation');
  addB('Cleanup inline during creation (no separate cron)');
  addH3('6.6.3 Version Viewer');
  addB('Right-side drawer with paginated version table');
  addB('Each row: timestamp, source, editor name (shared notes)');
  addB('"View Changes": diff view in new tab (title, content HTML diff, tags, attachments, video)');
  addH3('6.6.4 Version Restore');
  addB('One-click restore from any version');
  addB('Current state saved as new version before restore (non-destructive)');
  addB('Atomic update of all note fields from snapshot');
  addH2('6.7 Trash & Soft Delete');
  addH3('6.7.1 Mechanism');
  addB('isDeleted=true, deletedAt=now()');
  addB('All queries filter isDeleted=false by default');
  addB('Index on isDeleted for performance');
  addH3('6.7.2 Shared Note Deletion');
  addB('Remove all NoteShare records immediately');
  addB('Notify each affected user');
  addB('Note disappears from "Shared with Me" instantly');
  addH3('6.7.3 Restore');
  addB('isDeleted=false, deletedAt=null');
  addB('Status reset to "draft"');
  addB('Previously shared users NOT auto-re-added');
  addH3('6.7.4 Permanent Deletion');
  addB('Configurable retention: default 30 days (UserPreference.trashRetentionDays)');
  addB('Options: delete_versions_only (default) or delete_note_and_versions');
  addB('Weekly cron (Sunday 3 AM) handles purge');
  addH2('6.8 Archive System');
  addH3('6.8.1 Behavior');
  addB('Read-only; must unarchive to edit');
  addB('Cannot be soft-deleted directly (unarchive first)');
  addB('Hidden from default My Notes; visible via "Archived" filter');
  addB('Excluded from default search; "Include archived" toggle available');
  addH3('6.8.2 Archive + Sharing');
  addB('Warning popup when archiving shared note');
  addB('If confirmed: remove all NoteShares, notify users');
  addB('Previous collaborators can request re-access (1h cooldown)');
  addB('Owner can grant or decline requests');
  addH3('6.8.3 Unarchive');
  addB('Restores to previous status (published returns as published, not draft)');
  addB('Notifies previously shared users that note is available again');
  addB('Bulk archive/unarchive supported');
  addH2('6.9 File Management');
  addB('Provider: Supabase Storage');
  addB('Upload: signed URL (60s TTL), client uploads directly');
  addB('Path: {userId}/{noteId}/{timestamp}_{filename}');
  addB('Images: max 1MB, webp/jpeg/png');
  addB('PDFs: max 3MB per note');
  addB('Avatars: image/*, no size limit');
  addB('Orphan cleanup: auto-delete removed files on note update');
  addH2('6.10 User Preferences');
  addB('Trash retention days (default 30)');
  addB('Auto-delete behavior: delete_versions_only | delete_note_and_versions');
  addB('Theme: dark/light mode (next-themes)');
  addH1('7. UI/UX Design Specifications');
  addH2('7.1 Layout');
  addP('Fixed vertical left sidebar (240px, collapsible to 64px icon-only). Main content area fills remaining space. Responsive design for various screen sizes.');
  addH2('7.2 Navbar (Left Sidebar)');
  addH3('Zone 1 - Identity (Top)');
  addB('App logo + "Galaxy Note" - click navigates to My Notes');
  addB('User avatar (circular) + display name + provider badge - click opens profile settings');
  addH3('Zone 2 - Navigation (Middle)');
  addB('My Notes (FileText icon) - owned notes list. Badge: total count. Active: accent highlight.');
  addB('Shared with Me (Users icon) - shared notes. Badge: unread/new count.');
  addB('Notifications (Bell icon) - notification feed. Badge: unread count.');
  addB('Trash (Trash2 icon) - soft-deleted notes. Badge: trashed count.');
  addH3('Zone 3 - Actions (Bottom, Pinned)');
  addB('New Note (Plus icon) - primary CTA, full-width or icon-only when collapsed');
  addB('Settings (Settings icon) - profile/account settings');
  addB('Dark Mode toggle (Moon/Sun icon) - persisted theme switch');
  addB('Log Out (LogOut icon) - session destruction + redirect to login');
  addH3('Collapsed State (64px)');
  addB('Icons only with tooltips on hover');
  addB('Active item: left accent border (2-3px) + muted background');
  addB('All Lucide icons: 20px, consistent stroke-width');
  addH2('7.3 Note List View');
  addB('Table with pagination');
  addB('Columns: title (ellipsis), status badge, tags, last updated, actions');
  addB('Filters: status, search by title/tags (case-insensitive)');
  addB('Archived notes: separate filter, muted style, excluded from main count');
  addH1('8. Edge Cases & Mitigations');
  addH2('8.1 Concurrent Editing Conflict');
  addBP('Problem: ','Two WRITE users editing same note simultaneously.');
  addBP('Solution: ','Optimistic locking via version field. Client sends version with save. Server rejects 409 if mismatch, returns latest content for diff/merge UI.');
  addH2('8.2 OAuth Email Collision');
  addBP('Problem: ','User has email/password account, tries OAuth with same email.');
  addBP('Solution: ','Toast: "Existing account found. Log in with password to link." Password verification required before merge.');
  addH2('8.3 Session Expiry During Editing');
  addBP('Problem: ','JWT (1h) expires mid-edit, risking data loss.');
  addBP('Solution: ','(1) localStorage auto-save every 30s. (2) Proactive refresh when <10 min left. (3) Background refresh every 5 min + on visibility change. (4) 401 retry with refresh.');
  addH2('8.4 Notification Spam');
  addBP('Problem: ','Rapid edits generate excessive notifications.');
  addBP('Solution: ','(1) 2s debounce on auto-save. (2) Backend: only notify if >15 min since last notification. Max 4/hour per note per collaborator.');
  addH2('8.5 READ User Attempting WRITE');
  addBP('Problem: ','Undefined behavior when READ user tries to edit.');
  addBP('Solution: ','(1) Frontend: editable={permission==="WRITE"}, hide save button. (2) Backend: guard throws 403 if READ.');
  addH2('8.6 Invalid YouTube Video');
  addBP('Problem: ','Malformed URL or deleted video after saving.');
  addBP('Solution: ','(1) Regex validation on save. Optional oEmbed check. (2) onError handler shows "Video unavailable" fallback with clickable URL.');
  addH2('8.7 Version History Cap');
  addBP('Problem: ','Unbounded version accumulation.');
  addBP('Solution: ','Hard cap at 30. Oldest deleted on new creation. Inline cleanup (no cron).');
  addH2('8.8 Sharing with Unregistered Users');
  addBP('Problem: ','Email not in system.');
  addBP('Solution: ','"Send Invite Email" button. Registration link with pre-filled email + 7-day token. Auto-create NoteShare after registration.');
  addH2('8.9 Soft Delete + Shared Visibility');
  addBP('Problem: ','Should shared users see trashed notes?');
  addBP('Solution: ','Immediately remove NoteShares + notify. On restore: status=draft, shares NOT re-added.');
  addH2('8.10 Forgot Password');
  addBP('Problem: ','No reset flow from login page.');
  addBP('Solution: ','32-byte token (15 min), Nodemailer email, /reset-password page. Resend disabled 1 min with countdown.');
  addH1('9. Scheduled Cleanup (Cron Jobs)');
  addP('Weekly cron job (Sunday 3:00 AM) via @nestjs/schedule:');
  addB('Purge stale note versions for deleted notes beyond retention period');
  addB('Purge expired/revoked refresh tokens');
  addB('Purge expired password reset tokens');
  addB('Purge expired note invite tokens (7-day window)');
  addB('Purge expired notification mutes');
  addB('Auto-delete per UserPreference.autoDeleteBehavior setting');
  addH1('10. Security Considerations');
  addB('Password hashing: bcrypt, 12 salt rounds');
  addB('JWT access tokens: 1h TTL, encrypted NextAuth cookie');
  addB('Refresh tokens: 24h TTL, httpOnly cookie, rotation with stolen token detection');
  addB('CSRF protection: CsrfMiddleware on mutation endpoints');
  addB('Request tracing: UUID RequestIdMiddleware');
  addB('Input validation: Zod (frontend) + class-validator (backend) - defense in depth');
  addB('File upload: signed URLs (60s TTL), type and size validation');
  addB('Authorization guards: note ownership + share permissions on all endpoints');
  addB('OAuth: X-Internal-Secret header for server-to-server calls');
  addB('Database: PgBouncer + SSL');
  addB('Credentials: environment variables only, never in codebase');
  addH1('11. Testing Strategy');
  addH2('11.1 Backend');
  addB('Jest + ts-jest, supertest for E2E');
  addB('*.spec.ts co-located with source');
  addB('Coverage via collectCoverageFrom');
  addH2('11.2 Frontend');
  addB('ESLint: Next.js core-web-vitals');
  addB('TypeScript strict mode');
  addH2('11.3 Manual Testing Checklist');
  addB('Auth flows: register, login (credential + OAuth), password reset, token refresh');
  addB('Note CRUD: create all fields, autosave, versioning, diff view');
  addB('Sharing: registered/unregistered users, permissions, archive/delete shared notes');
  addB('Edge cases: concurrent edit (409), OAuth collision, notification rate limiting');
  addB('UI: sidebar collapse, responsive, dark/light theme');
  addH1('12. Future Considerations & Roadmap');
  addB('Real-time collaborative editing (CRDT/OT-based)');
  addB('Full-text search with PostgreSQL tsvector');
  addB('Export: PDF, Markdown, plain text');
  addB('Folders/notebooks for hierarchical organization');
  addB('API rate limiting per user');
  addB('Mobile: React Native or PWA');
  addB('AI features: summarization, auto-tagging, smart search');
  addB('Audit log for shared note activity');
  addB('Archive expiry: configurable auto-delete');
  addB('Storage optimization for long-archived notes');
  addB('Webhook integrations: Slack, Discord, email');
  var firstChild = body.getChild(0);
  if (firstChild.getType() === DocumentApp.ElementType.PARAGRAPH && firstChild.asParagraph().getText() === '') {
    body.removeChild(firstChild);
  }
}
